## Bernouli Random Variable

In [ ]:
import tensorflow_probability as tfp
import tensorflow as tf


In [ ]:
keeping_prob = 0.7
r = tfp.distributions.Bernoulli(probs=keeping_prob, dtype=tf.float32).sample(sample_shape=(10, 1))

In [ ]:
r

<tf.Tensor: shape=(10, 1), dtype=float32, numpy=
array([[0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.]], dtype=float32)>

In [ ]:
y_prev = tf.random.normal((10, 1))
y_prev

<tf.Tensor: shape=(10, 1), dtype=float32, numpy=
array([[-0.30535084],
       [-1.2872857 ],
       [-0.9808804 ],
       [ 0.52876496],
       [-1.3633162 ],
       [ 0.59784055],
       [-1.662759  ],
       [ 0.8442763 ],
       [ 0.01131978],
       [ 1.3368016 ]], dtype=float32)>

In [ ]:
y_new = tf.math.multiply(y_prev, r)
y_new

<tf.Tensor: shape=(10, 1), dtype=float32, numpy=
array([[-0.        ],
       [-1.2872857 ],
       [-0.9808804 ],
       [ 0.52876496],
       [-1.3633162 ],
       [ 0.        ],
       [-1.662759  ],
       [ 0.8442763 ],
       [ 0.01131978],
       [ 1.3368016 ]], dtype=float32)>

## Use Dropout Layer

In [ ]:
from tensorflow import keras

In [ ]:
model = keras.models.Sequential([
    keras.layers.Flatten(input_shape=[28, 28]),
    keras.layers.Dropout(rate=0.5),
    keras.layers.Dense(300, activation="elu", kernel_initializer="he_normal"),
    keras.layers.Dropout(rate=0.5),
    keras.layers.Dense(100, activation="elu", kernel_initializer="he_normal"),
    keras.layers.Dropout(rate=0.5),
    keras.layers.Dense(10, activation="softmax")
])
model.compile(loss="sparse_categorical_crossentropy", optimizer="nadam", metrics=["accuracy"])
# n_epochs = 2
# history = model.fit(X_train_scaled, y_train, epochs=n_epochs,
#                     validation_data=(X_valid_scaled, y_valid))

In [ ]:
model.summary()


Model: "sequential_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
flatten_3 (Flatten)          (None, 784)               0         
_________________________________________________________________
dropout (Dropout)            (None, 784)               0         
_________________________________________________________________
dense_10 (Dense)             (None, 300)               235500    
_________________________________________________________________
dropout_1 (Dropout)          (None, 300)               0         
_________________________________________________________________
dense_11 (Dense)             (None, 100)               30100     
_________________________________________________________________
dropout_2 (Dropout)          (None, 100)               0         
_________________________________________________________________
dense_12 (Dense)             (None, 10)               